#!/bin/sh
alias vu="vagrant up"
alias vp="vagrant provision"
alias vup="vagrant up --provision"
alias vdf="vagrant destroy -f"
alias sv="~/bin/vagrant-docker-sudo.sh"
alias svu="~/bin/vagrant-docker-sudo.sh up"
alias svp="~/bin/vagrant-docker-sudo.sh provision"
alias svup="~/bin/vagrant-docker-sudo.sh up --provision"
alias svdf="~/bin/vagrant-docker-sudo.sh destroy -f"
