#!/usr/bin/env bash

#set -x

is_options(){
  grep --quiet "^--" <<< "$1"
}

# Ignore any first arg with --
if is_options "$1";
then
  shift
fi

subject="$@"

if test -z "$subject";
then
  echo "Hello World!"
else
  echo "Hello ${subject}!"
fi

