#!/usr/bin/env zsh

if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

MY_GROUP=me_myself_and_i
chmod -R +a "group:${MY_GROUP} allow list,add_file,search,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" /usr/local/*
chgrp -R "$MY_GROUP" /usr/local/*
chmod -R g+rwX /usr/local/*
chown -R m /usr/local/{Cellar,Caskroom,Homebrew}
