#!/bin/sh

# A micro script to open a my journal

#JJOURNAL_PATH="$HOME/.local/jjournal/$(date +%Y-%m-%d).md"
JJOURNAL_PATH="$HOME/Documents/journal/jj.md"

mkdir -p "$(basename "$JJOURNAL_PATH")"
nvim -u ~/.jjvimrc "$JJOURNAL_PATH"
