#!/usr/bin/env bash

cd ~/.dots

echo "❆ Update flake"
nix flake update

# Nix don't update brew as far as I understand
echo "🍺 Updating brew"
brew update

## 2021-04-18 TODO: Only path the specific variable nix & nix-darwin needs
echo "👹 Updating nix-darwin"
m switch

echo "🍺 Cleanup brew cache"
brew cleanup --prune 14

echo "👹 Collect nix garbage"
sudo nix-collect-garbage --delete-older-than 14d

echo "👹 Dedup nix store"
sudo nix store optimise

# Make sure dvp is my login keyboard
echo "⌨️  Update my login keyboard"
sudo cp ~/Library/Preferences/com.apple.HIToolbox.plist /Library/Preferences/
sudo chmod 644 /Library/Preferences/com.apple.HIToolbox.plist
