on: [push]

name: Build
jobs:
  build:
    name: Build
    runs-on: macos-10.15
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v16
        #with:
        #  nix_path: nixpkgs=channel:nixpkgs-21.11-darwin

        #- name: Set up cache
        #  uses: zombiezen/setup-nix-cache-action@v0.1.0
        #  with:
        #    substituters: s3://mdots?endpoint=https://https://mdots.s3.fr-par.scw.cloud/
        #    secret_keys: ${{ secrets.NIX_PRIVATE_KEY }}
        #    aws_access_key_id: ${{ secrets.SCALEWAY_S3_ACCESS_KEY}}
        #    aws_secret_access_key: ${{ secrets.SCALEWAY_S3_SECRET_KEY }}
    - name: Setup AWS profile
      run: |
        mkdir ~/.aws
        cat <<EOF > ~/.aws/credentials
        [default]
        aws_access_key_id=${{ secrets.SCALEWAY_S3_ACCESS_KEY }}
        aws_secret_access_key=${{ secrets.SCALEWAY_S3_SECRET_KEY }}
        EOF
        #- name: Check AWS config
        #  run: |
        #    cat ~/.aws/credentials
        #    cat /etc/nix/nix.conf
    - name: Add nix channels
      run: |
        nix-channel --add https://channels.nixos.org/nixpkgs-21.11-darwin nixpkgs
        nix-channel --add https://channels.nixos.org/nixpkgs-unstable unstable
        nix-channel --update
    - name: Install Nix Darwin
      run: |
        nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
        ./result/bin/darwin-installer
    - name: Build my system
      run: |
        source /etc/static/bashrc
        darwin-rebuild build -I darwin-config=nixpkgs.symlink/darwin-configuration.nix
      #--extra-substituters=s3://mdots?endpoint=https://https://mdots.s3.fr-par.scw.cloud/
